### ISSUE TITLE
Linearising the GFA graph with BioGraph and visualing with Panache

### ISSUE THREAD

**Issue by brettChapman** [pangenome/pggb#158]
Hi

I've just come across a tool for enabling pangenome graph exploration using Panache, which accepts a linearised graph produced by BioGraph, given a GFA file.

https://github.com/SouthGreenPlatform/panache
https://github.com/nguyetdang/BioGraph.jl

I was wondering if you're aware of these tools, and if the PGGB GFA file would be compatible with it, before i jumped down this rabbit hole to try it out.

Thanks.

**Comment by subwaystation** [comment]
Hi @brettChapman,

we didn't try it,yet. 
However, I sent @SingingMeerkat and @nguyetdang a PGGB HLA graph to test it out. That's as far as we got.
I was told that the PGGB GFA file should be compatible, but no one has tested it, yet. Hoping that we will see something soon.
Best,
Simon

**Comment by brettChapman** [comment]
Thanks @subwaystation 

I'm attempting to try and use BioGraph now to linearise my graphs. I found a few issues with it I posted on the BioGraph repo (https://github.com/nguyetdang/BioGraph.jl/issues/21), particularly with the get_gfa and get_fasta functions. The documentation isn't very clear with how to convert a GFA to a linear form, or the output format I should be converting it to.

I'm also trying GFAtools gfa2bed (https://github.com/lh3/gfatools), but I think it will only handle rGFA formats, which I don't think the PGGB GFA files are compatible with.

**Comment by brettChapman** [comment]
I managed to get something working with BioGraph using the following method and their example GFA. The output is still a GFA, so I have no idea how to get a linearised form of the graph:
```
import Pkg; Pkg.add(url="https://github.com/brettChapman/BioGraph.jl", rev="main"); Pkg.add("GraphIO"); Pkg.add("ParserCombinator"); Pkg.add("JuMP"); Pkg.add("BioSequences"); Pkg.add("CSV"); Pkg.add("Cbc"); Pkg.add("LightGraphs"); Pkg.add("Suppressor"); using BioGraph; using BioGraph: Weight, NodeLabel, EdgeLabel; using LightGraphs; using Suppressor; using JuMP; using BioSequences; using CSV; using ParserCombinator; using Cbc; gfa_result = read_from_gfa("gfa_sample_1.gfa"); res = find_graph_component(gfa_result); longest = find_longest_path(res.graph[1], Cbc.Optimizer, is_weighted = false); get_gfa(longest, "longest.gfa");
```

input:
```
ubuntu@node-0:/data/biograph_builds/BioGraph.jl/test/data$ cat gfa_sample_1.gfa 
H	VN:Z:1.0
S	1	AT
S	2	TTAACTCCATCTTTGAGAAACATTTAATAATGTAATGTGTTTGT
S	3	CA
S	4	TACAGGGTGA
S	5	A
S	6	TACAGATGCAC
L	1	+	2	+	0M
L	2	+	3	+	0M
L	3	+	4	+	0M
L	4	+	5	+	0M
L	4	-	2	+	0M
L	5	+	6	+	0M
```

output:
```
ubuntu@node-0:/data/biograph_builds/BioGraph.jl/test/data$ cat longest.gfa 
H	VN:Z:1.0
S	1	AT	
S	2	TTAACTCCATCTTTGAGAAACATTTAATAATGTAATGTGTTTGT	
S	3	CA	
S	4	TACAGGGTGA	
S	5	A	
S	6	TACAGATGCAC	
S	4	TACAGGGTGA	
L	1	+	2	+	0M	
L	2	+	3	+	0M	
L	3	+	4	+	0M	
L	4	+	5	+	0M	
L	5	+	6	+	0M	
L	4	-	2	+	0M	
P	LongestPath	1+,2+,3+,4+,5+,6+	0M,0M,0M,0M,0M
```

**Comment by brettChapman** [comment]
There was a bug in their get_gfa and get_fasta functions. A ';' in their function inputs rather than ','. I forked their repo to fix it.

The Panache paper refers to BioGraph to linearise the data for input into Panache, but it isn't quite clear which functions linearises the graph.

**Comment by ekg** [comment]
The longest path annotation gives the impression that they expect a
directed acyclic graph.

**Comment by brettChapman** [comment]
@ekg Possibly. Can the PGGB GFA be converted to a directed acyclic graph? I read a bit more on Panache and it looks like the format gets converted to a JSON file, which would make sense if converting from a DAG.

I just came across another tool which does linearisation of graphs and outputs a GFA. Worth having a look too https://github.com/anialisiecka/alibi

@francoissabot might be able to provide some more insight as well to BioGraphs functionality, as he appears to be involved in both BioGraph and Panache.

**Comment by SingingMeerkat** [comment]
Hi all!
Thanks for the question, Panache is built so that it can take specific BED-like format showing presence absence of pangenomic blocks, and therefore graph files need to be linearized / ordered prior to their display. [@nguyetdang](https://github.com/nguyetdang) is working on biograph.jl and a tool to convert graph outputs into other formats, including a Panache-compatible one.
Her tool is mainly based on minigraph outputs, ie. rGFA, however since rGFA is only an extension of 'basic' GFA, it should work with GFA file from other tools (as long as there is no overlap between node, from what I get). There is not much documentation yet but it is in preparation.

As for the detail of the command line I wouldn't be able to help much but [@nguyetdang](https://github.com/nguyetdang) would have a better idea, and [@francoissabot](https://github.com/francoissabot), our PhD advisor, could help with the theory behind it. I'll ask them when I see them, hopefully tomorrow, else later this week.

**Comment by SingingMeerkat** [comment]
As for the internal format used by Panache, it converts the BED-like Presence Absence matrix into a JavaScript Object, with a syntax close to JSON indeed, after a few parsing and modifying steps. For Panache instances based on specific files it is easier to start directly with the pre formated JSON-like format (that's what we did with our [BananaGenomeHub](https://banana-genome-hub.southgreen.fr/content/panache) for instance).
I've added a bit of documentation about how to build these files but since it might not be that straightforward I can help with that.


In my original idea of Panache it would display pangenomic blocks more or less based on their order of appearance within each genome, and blocks with multiple occurences in different places would be cloned, creating one panBlock for every position (basically creating an unrolled graph with block redundancy when they appear on multiple occasions, ie. DAG since we try to avoid loops). The bottom track was made with the idea of highlighting the "identity" relations between such duplicated blocks, even though it has not been used to its full potential yet.
In its current state Panache will simply display blocks of presence absence. Their positions / order, and wether they are cloned within the pangenome depends on how the file has been built (you could decide that the blocks are nodes from a graph, with a specific order, kmers on a reference with different present statuses in the genomes, genes positionned on a panreference of sort, or even a simple repertoire of genes where the position is just used to differenciate them visually).

**Comment by brettChapman** [comment]
Thanks @SingingMeerkat for your input. I'm familiar with JSON formats and have used D3.js before with JSON data, so I should have no problems with getting the prepared data into Panache. Based on the documentation you provided it looks pretty straight forward going from BED-like format to JSON-like for Panache to read in. The main bottleneck now is how to go from GFA to BED-like format.

I've looked at all the functions with BioGraph.jl, and none seem to provide that, except maybe the get_terminus function which outputs sink nodes and source nodes in CSV. Perhaps @nguyetdang could provide some insight. I have a feeling the public repo for BioGraph.jl is an alpha version, while she's working on the latest version in a private repo. 

I've used the following:
```
import Pkg; Pkg.add(url="https://github.com/brettChapman/BioGraph.jl", rev="main"); Pkg.add("GraphIO"); Pkg.add("ParserCombinator"); Pkg.add("JuMP"); Pkg.add("BioSequences"); Pkg.add("CSV"); Pkg.add("Cbc"); Pkg.add("LightGraphs"); Pkg.add("Suppressor"); using BioGraph; using BioGraph: Weight, NodeLabel, EdgeLabel; using LightGraphs; using Suppressor; using JuMP; using BioSequences; using CSV; using ParserCombinator; using Cbc; gfa_result = read_from_gfa("gfa_sample_1.gfa"); res = find_graph_component(gfa_result); longest = find_longest_path(res.graph[1], Cbc.Optimizer, is_weighted = false); get_gfa(longest, "longest.gfa"); get_terminus(res.graph[1], "terminus");
```
 
terminus output:
```
cat terminus_sink_node.csv 
Label,Direction,Sequence,Information
6,+,TACAGATGCAC,

cat terminus_source_node.csv
Label,Direction,Sequence,Information
4,-,TACAGGGTGA,
1,+,AT,
```

longest path:
```
cat longest.gfa 
H	VN:Z:1.0
S	1	AT	
S	2	TTAACTCCATCTTTGAGAAACATTTAATAATGTAATGTGTTTGT	
S	3	CA	
S	4	TACAGGGTGA	
S	5	A	
S	6	TACAGATGCAC	
S	4	TACAGGGTGA	
L	1	+	2	+	0M	
L	2	+	3	+	0M	
L	3	+	4	+	0M	
L	4	+	5	+	0M	
L	5	+	6	+	0M	
L	4	-	2	+	0M	
P	LongestPath	1+,2+,3+,4+,5+,6+	0M,0M,0M,0M,0M
```

**Comment by subwaystation** [comment]
Thanks @brettChapman for digging into this :)
The longest path in a chromosome-wise built graph with PGGB is usually just the connection of the largest component in that graph. However, it seems that BioGraph.jl is expecting that the nodes are reflecting a reference, so the graph is a DAG. That's the case for the rGFA format, at least. So I doubt you can use the PGGB GFAs out of the box. Also, `odgi untangle` could only deliver you a BEDPE file which would not fit the BED requirement. But maybe we can sort this out. I didn't quite understand the interaction between the (r)GFA and the BED file. What has to be in the BED file?

Looking at the Alibi paper, I realized that the EADES sorting algorithm was also part of ODGI. But it turns out our PG-SGD sorting algorithm is the best to linearize a graph on a global scale. However, it won't give you a DAG. If a DAG is a requirement for Panache, then maybe @ekg has more ideas? 
I am also making the bold assumption, based on experience,that Alibi won't scale, because it is written in Python.

Both Alibi and Panache are not aware of already existing paths. Maybe that's something to consider.

**Comment by brettChapman** [comment]
No problem @subwaystation. If I can get the PGGB GFA into Panache it will really help my barley pangenome project along to finalise and publish.

What if we used ```odgi untangle``` to produce a BEDPE format for every path in the graph, and then somehow go from BEDPE to BED? The formats between BEDPE and BED aren't all that different. Could that work or is it too simple of an approach to get something compatible?

@SingingMeerkat @nguyetdang do you have an example BED-like file which Panache requires as input to give us an idea of the exact format we need to try and aim towards?

**Comment by subwaystation** [comment]
Hi @brettChapman. Your `odgi untangle` suggestions sounds good to me, but it is unclear to me how the GFA and the BED file must be shaped, in order to produce the binary matrix required by Panache for visualization. 
However, `odgi untangle` can also give you a PAF file. You could plug this into `seqwish` again. This might even produce a DAG as the graph was unfolded according to a reference. But, if the reference has repeated sequences, a DAG may not be possible. I didn't explore this, maybe @AndreaGuarracino knows more?

I also had a look at @SingingMeerkat's Panache documentation, but the interaction between GFA, BED, and the binary matrix is unclear to me. Maybe we don't even need a longest path, but we can just take an existing one. For example, just take the path which was selected as the "reference" in `odgi untangle`. Then BEDPE -> BED. And maybe you are good to go. But that's just speculating.

**Comment by ekg** [comment]
What I don't understand is why panache can't just use the graph binary
matrix implied by the sorted GFA. What is the reference basis adding? Just
a particular linearization? Could we make a consensus longest path thay
covers all nodes in order?

**Comment by brettChapman** [comment]
@ekg @subwaystation From what I've read up on Panache a reference is needed as the Panache interface uses a reference for the genomic coordinates and incorporation of gene coordinates, as a GFF file can be provided along with the pangenome PAV matrix.

If Panache works with rGFA. Would running seqwish again with a PAF file with a chosen reference not produce a rGFA which would be a DAG? To avoid any repeats in the rGFA could we not clip out repeat regions in the reference? Is it possible to do that using tools such as ```vg chop``` or one of ODGI tools? Also I came across ```odgi flatten``` which linearises the graph and produces a BED file, so this is something which we could use once I have an rGFA after running seqwish on the PAF file. Alternatively I could use gfatools gfa2bed (https://github.com/lh3/gfatools), which accepts rGFA.

**Comment by brettChapman** [comment]
I produced a new GFA based on a reference using a PAF file from ```odgi untangle``` and feeding it into seqwish. Unfortunately this GFA can't be read by gfatools, so maybe it's not a proper rGFA even though it's based on a single reference, or there are other subtle formatting differences.

I also tried ```odgi flatten``` but found it doesn't work. It doesn't produce the right kind of BED file. I'm going to try and produce a BEDPE file using ```odgi untangle``` instead and see if I can convert it to a BED file by removing some unnecessary columns.

**Comment by subwaystation** [comment]
@brettChapman I think `vg convert` has an option to go from GFAv1 to rGFA. But, we didn't try it, yet.
It says:

```
gfa options:
    -P, --rgfa-path STR    write given path as rGFA tags instead of P-line (use with -f, multiple allowed, only rank-0 supported)
    -Q, --rgfa-prefix STR  write paths with given prefix as rGFA tags instead of P-lines (use with -f, multiple allowed, only rank-0 supported)
```
However, I don't know if `vg convert` can actually do this in a meaningful way for a graph constructed by PGGB.

**Comment by brettChapman** [comment]
Thanks @AndreaGuarracino

If I output ```odgi untangle``` to BEDPE, would that still be low resolution not at the base-level? This may not be a problem as the PAV matrix that Panache excepts as input looks at pangenome blocks and as far as I can tell, isn't concerned with base-level variation like identifying SNPs. Looking at an example of Panache in action, it doesn't look like I can zoom in to base level details. https://banana-genome-hub.southgreen.fr/content/panache @SingingMeerkat @nguyetdang would this be an accurate assumption? Do we need a base-level accurate BED file for Panache?

If I need base-level PAF, is there away to get from PAF to BED without losing the base-level information?

Thanks @subwaystation I'll also try ```vg convert``` and see how I go.

**Comment by brettChapman** [comment]
Thanks @SingingMeerkat for your detailed explanation and your example BED-like file.

From my understanding now, what I actually need to get from my GFA is a prescence/abscence matrix of node blocks, with chromosome name in the fist column, second and third columns start and end coordinates of the nodes, and genome names along rows, with added meta data in the first several columns, which can be '.'. Therefore I don't actually need a BED file in the traditional sense, I just need a PAV matrix of nodes with coordinates and then format it afterwards to be BED-like.

@ekg @subwaystation @AndreaGuarracino Is it possible to get node information out like this with their chromosome coordinates in a prescence/abscence matrix, and then input this into some fancy scripting in awk to get the extra mandatory columns?

**Comment by ekg** [comment]
odgi untangle will almost give you this. The reference requirement is a
problem though. If Panache could work on reference free or multi-reference
graphs that'd be ideal. It's trivial to generate a linearized presence
absence matrix over the graph node order. But the basis space is the graph
itself, not a specific reference. Reference coordinates for any included
path are of course available in the graph, but to access them quickly
requires indexing that's both simpler and different than the hierarchical
model in minigraph. It'd be great if Panache could work on this general
context, but if not I guess we need to start working on an alternative
browser.

**Comment by brettChapman** [comment]
Thanks @ekg 

You're right. From my PAF file given the single reference and multiple query paths with ```odgi untangle``` I can get something along the lines of a PAV matrix. I'll start on a script to build a PAV matrix from it. It might take a bit of fiddling around, but it should work in theory and be compatible with Panache.

**Comment by SingingMeerkat** [comment]
You're welcome @brettChapman !

The PAV + coordinates are the core component of the files, indeed. Let me know whenever you need help with Panache again, I hope the script building will go smoothly.

@ekg Being based on a pre defined coordinate system is definitely a limitation here. Our approach took inspiration from various "pangenomes" and tried to take into account different cases (gene pangenomes, blocks from multiple sequence alignments, graph-derivatives...), and it limits itself to front-end, no back-end.
A tool dedicated purely to graph, with the possibility to change reference on-the-fly thanks to the datastructure would be ideal for users with graph data. Unfortunately such modifications to Panache are not part of our current developments plans, at least for now. I believe the newest version of pantograph could achieve the reference change but I'm unsure when it will be available, or at what pricing option.

**Comment by brettChapman** [comment]
Thanks @SingingMeerkat

I've now written a Python script to generate the BED/PAV matrix for Panache. I'm now attempting to get Panache installed and running with some of your example data before I load in my files. I have a newick file and a GFF file as well. I tried through the Docker method  but there appears to be some problem. I'll open an issue on the Panache repo.

**Comment by ekg** [comment]
There is a tool called odgi flatten which make some attempt to build a
similar kind of matrix. The reference sequence is the concatenation of all
the nodes. Paths are described with BED records that map into this
reference.

**Comment by subwaystation** [comment]
@brettChapman Could you please share your approach, tools, and command lines somewhere? Thanks!

**Comment by AndreaGuarracino** [comment]
🍿

**Comment by brettChapman** [comment]
Sure @subwaystation 

I'll create a GitHub repo with my workflow. I'm currently testing out the PAV matrix to see if it works as it should with Panache.

**Comment by brettChapman** [comment]
@subwaystation and @AndreaGuarracino my approach to linearise the pangenome graph and generate a PAV binary matrix for use with Panache you can find here: https://github.com/brettChapman/paf2pav

**Comment by AndreaGuarracino** [comment]
@brettChapman, thank you for sharing it. In case you are interested in different approaches, please note that `odgi pav` is coming (together with a little tutorial of it): https://github.com/pangenome/odgi/pull/371.

**Comment by brettChapman** [comment]
Thanks @AndreaGuarracino ```odgi pav``` looks great! I'll try it out.

**Comment by brettChapman** [comment]
@AndreaGuarracino I'm just looking at the parameters from ```odgi pav``` now and it requires a BED file as input. Would this be a BED file which ```odgi flatten``` outputs? or some other BED file based on coordinates in one of the genomes only, like a conventional BED file with a single reference?

**Comment by brettChapman** [comment]
@AndreaGuarracino I had a look at your tutorials, makes sense now. The method using ```odgi untangle``` is similar to mine. I'll try it out and compare results.

**Comment by brettChapman** [comment]
@AndreaGuarracino I found both PAV matrices from each method to be identical if using ```-B 0``` with ```odgi pav```. Setting this to 0.5, I do find some cases where a pangenome block is missing instead of present. How is the PAV ratio determined? By the number of gaps in the aligned region? I guess using ```-B 0``` would be a conservative approach, in saying that if anything aligns at all, consider it present, otherwise absent. Which is basically the approach my paf2pav script takes.

**Comment by AndreaGuarracino** [comment]
Hi @brettChapman, thank you for your feedback.

The input BED file can be anything and it can present multiple paths used as target/reference paths. I've just added another `odgi untangle | odgi pav` example where PAVs are identified with respect to all paths in the pangenome graph (https://odgi.readthedocs.io/en/latest/rst/tutorials/presence_absence_variants.html#how-to-get-a-bed-file-odgi-untangle). You will find also another example with `odgi flatten | odgi pav` (https://odgi.readthedocs.io/en/latest/rst/tutorials/presence_absence_variants.html#how-to-get-a-bed-file-odgi-flatten).

Regarding the PAV ratio, for a given path range `PR` and path `P`, it is the ratio between the sum of the lengths of the nodes in `PR` that are crossed by `P` divided by the sum of the lengths of all the nodes in `PR` (#bps crossed by `P` in `PR` / #bps in `PR`). Each node is considered only once, so loops are not (yet) considered. Your interpretation of `-B` is correct: setting it very low would be equivalent to putting `1` in the matrix for all paths that 'touch' the range, also if they cover a tiny portion of it (the minimum would be 1 base).
