### ISSUE TITLE
Help with parameters for a small insect genome

### ISSUE THREAD

**Issue by RenzoTale88** [pangenome/pggb#159]
Hi,
I'm trying to run pggb on a set of five assemblies of an insect genome. The mash distances (`-32 -s 10000`) ranges between 0.004 to 0.009, and the genome size is ~230Mb.
I've ran a test using the human parameters described in the README (`-p 98 -s 100000 -n 90 -k 311 -G 13117,13219`) but I'm wondering if I can perhaps improve the pangenome quality by tweaking the parameters.

Thanks in advance for any help
Andrea

**Comment by subwaystation** [comment]
Hi @RenzoTale88,

one way to evaluate the quality of a pangenome is to do variant calling using `vg deconstruct` and compare the resulting VCF with a truth set or with the current state-of-the-art reference-based variant calling. You could take a look at a region of interest in your pangenome and compare it with existing biological knowledge.

Since your mash distance seems fairly low, you could opt for a higher `-p`. Also, `-n 90` is for 90 haplotypes. I suspect, you would have to updates this for your 5 (or more, if phased assemblies) insect genomes. You could also try higher values for `-G`, since you have a low number of genomes, `abPOA` won't blow the memory limit as fast as when building a pangenome graph from 90 human haplotypes.
I hope this helps!

Best,
Simon

**Comment by AndreaGuarracino** [comment]
Having five assemblies, you should use `-n 5`. In general, to improve pangenome quality, you have to define what is quality for you. One way is to choose one or more metrics to optimize and take the parameter configuration that optimizes them all. For example, you may prefer a simpler graph (fewer nodes, fewer edges, etc...). With humans, we usually check precision / recall for variants identified with `vg deconstruct`. Furthermore, we also check the layouts of the graphs which must be globally linear (linear graphs are not necessarily the best representation, but they are certainly easier to 'understand'). I would suggest also inspecting _loci_ of interest to confirm that the biology you expect is there and correctly represented.
