### ISSUE TITLE
How to rename my scaffold name of two genomes

### ISSUE THREAD

**Issue by wyj-lzu** [pangenome/pggb#162]
Hi

I wanna run pggb based on two genomes according to the PanSN-spec. How can I understand the haplotype_id name? My scaffold name is like this :

genome 1 : X#1#scaffold1 X#2#scaffold2 ..... X#58#scaffold58
genome 2 : Y#1#scaffold1 Y#2#scaffold2 ..... Y#56#scaffold56

Could this fit the rule that pggb required?

Thanks : )
Yinjia

**Comment by ekg** [comment]
In a diploid case, the haplotype ID refers to the maternal or paternal
haplotypes. So you could have e.g. z#1#ctg9 z#2#ctg18. For polyploids or
haploids you would just increase or decrease the range. (The numeric IDs
can be replaced with strings identifying each haplotype subset of the
contig space, if you prefer to write e.g. maternal / paternal.)

If your assemblies aren't haplotype resolved, they are effectively haploid.
So put a single value in the second field of the PanSN names.

**Comment by wyj-lzu** [comment]
My assemblies aren't haplotype resolved (assembly by nextdenovo). 
What does the "single value" mean? Should the scaffold name should be :
genome 1 : X#1#scaffold1   X#2#scaffold2
or : 
genome1 : X#1#scaffold1   X#1#scaffold2

Thanks

**Comment by ekg** [comment]
genome1 : X#1#scaffold1 X#1#scaffold2

**Comment by lsoldini** [comment]
Hello pggb-team, 

I have a similar issue and I thought it may be better to re-open than create a new issue for the same problem. 

I am actually still struggling with header of the fasta files. 

I have these two assemblies (A and B) for my species. Each assembly is haplotype-resolved. So I thought using:
Assembly A: species#A#scf1, species#A#scf2, etc.
Assembly B: species#B#scf1, species#B#scf2, etc.

Then, I would like to run pggb with something like `pggb -p 85 -s 3000 -n 2 -H 2` (I changed the -n 1 to -n 2 since some parameters have changed with the new version of pggb). 

This works fine and I could verify SVs with SafFire as suggested. 

However, the `vg deconstruct` from the .gfa produces some weird .vcf output. I have tried many varieties, and I either end up with "conflict" rows in the .vcf (when I used directly the `-V` option in pggb) or some variants that should not be there (i.e., the .vcf includes variants from both assemblies). 

What would be the right way to set :

1. The headers of the sequences in the fasta ?
2. Either the `-V` option in the pggb pipeline or the parameters of the `vg deconstruct` function ?

Since I have tried several different things, I thought it may be easier to ask than write down the different things I've tried, but I can do so if it may help. 

Thank you for reading me !
Luca

**Comment by AndreaGuarracino** [comment]
Would you please report the command lines you tried? Have you specified `pggb ... -V 'species#'`?

**Comment by AndreaGuarracino** [comment]
Part of the problem could be that you have two haplotypes with the same sample ID, so you don't have a reference sample and another sample in which call variants with respect to the reference one.

**Comment by lsoldini** [comment]
Thank you, once again, for your very prompt answer!

I first tried following a previous suggestion, but I was not clear about the fact it was haplotype-resolved and I think this may have been misleading. Anyway, I used: `pggb -p 85 -s 3000 -v -V Species1:#,Species2:# -n 1 -H 2` and the headers were formated as 'Species1#1#scf..' and 'Species2#1#scf..'. This worked without any error, but then there were lines in the .vcf with "conflict" fields, and this led to errors using `vcfbub`. I used this with the previous pggb version, hence the `-n 1` and `-H 2` (but I have also tried with the last one, with parameters `-n 2` and `-H 2` and I had the same behaviour). 

Then, I tried with 'Species#1#scf...' and 'Species#2#scf...'. This time, since I had errors previously with `vg deconstruct`, I simply used the `pggb` without the `-v` parameter. I further used `vg deconstruct` on the .gfa. Specifically, I used `vg deconstruct -P Species -H SEP='#' -e -a`. While this worked with no error, it created a kind of mixed .vcf file containing variant which region belonged to both assemblies (i.e., in the 'region' field of the .vcf, there were 'Species#1#...' and 'Species#2#...' entries.

From your response, I think I should try with 'Species1#1#scf...' and 'Species2#2#scf...', so that the sample ID are not the same, is this correct ?

**Comment by lsoldini** [comment]
So, I've launched a run with 'Species1#1#scf ...' and 'Species2#2#scf ...' as headers for the .fasta, with the -v -V Species1:#,Species2:# parameters in `pggb`.

The two .vcf generated contains each thousands of entries with CONFLICT in the last column. For instance:
`Species1#1#scf9    10500616        >627493>627496  T       C       60      .       AC=0;AF=0;AN=0;AT=>627493>627495>627496,>627493>627494>627496;CONFLICT=Species2;NS=0;LV=1;PS=>642319>630521    GT      .`

What I can add:

- Both .vcf contains thousands (+65k and + 58k) CONFLICT entries
- Those conflicting entries are not specific to one scaffold or contig
- They seem to occur sequentially (i.e., many close to each other within a scaffold)
- I did not look where precisely, but one the only one that I looked corresponded to a region of a small translocated region

**Comment by lsoldini** [comment]
Ok, I thought the "CONFLICT" may be one reason why `vg construct` is throwing errors while trying to construct a graph from those .vcf (for downstream mapping). And, previously, `vcfbub` was not working when there were such field in the .vcf (but I guess this may have been due to something else co-occuring with those "CONFLICT" fields).

It seems now that the .vcf has indeed worked fine with `vcfbub`. 

I am not sure I understand the advantage of having a completely flattened graph ? The goal is usage with `vg construct` to further build a splice pangenome. Would this be required ? For now I was going with `vcfbub` only
