### ISSUE TITLE
smoothxg terminated by signal 6

### ISSUE THREAD

**Issue by petersudmant** [pangenome/pggb#182]
I'm having an issue with smoothxg. wfmash and seqwish run no problem, but I get an unexpected signal 6 termination subsequently. 

Any ideas? 

```
[odgi::unchop] unchopped 542 nodes into 269 new nodes.
[smoothxg::main] smoothed graph length 374213302bp in 9248321 nodes
[smoothxg::main] writing smoothed graph to /data/out//input.fa.gz.c55a916.7bdde5a.2a74e36.smooth.gfa
[smoothxg::main] building xg index from smoothed graph
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Command terminated by signal 6
smoothxg -t 24 -T 24 -g /data/out//input.fa.gz.c55a916.7bdde5a.2a74e36.smooth.1.gfa -w 18028 -X 100 -I .8500 -R 0 -j 0 -e 0 -l 4507 -P 1,19,39,3,81,1 -O 0.03 -Y 400 -d 0 -D 0 -m /data/out//input.fa.gz.c55a916.7bdde5a.2a74e36.smooth.maf -Q Consensus_ -C /data/out//input.fa.gz.c55a916.7bdde5a.2a74e36.cons,cons,100,1000,10000 -o /data/out//input.fa.gz.c55a916.7bdde5a.2a74e36.smooth.gfa
```

**Comment by AndreaGuarracino** [comment]
I have a sad hypothesis, that you've got the same problem as https://github.com/pangenome/pggb/issues/133, of which a full solution is still missing.

Before asking you for the input, would you please check if the `input.fa.gz.c55a916.7bdde5a.2a74e36.smooth.1.gfa` file has empty P lines?

**Comment by AndreaGuarracino** [comment]
@petersudmant thank you for sharing both `input.fa.gz.c55a916.7bdde5a.2a74e36.smooth.1.gfa` and `input.fa.gz.c55a916.7bdde5a.2a74e36.smooth.gfa` files.

Unfortunately, the sad prediction was right, in there are paths without any steps, but this is in the final graph, that you've also shared. The bug affects the consensus paths:

```
grep Consensus_36614 input.fa.gz.c55a916.7bdde5a.2a74e36.smooth.gfa

P       Consensus_36614         *
```

I have a possible solution, but it still needs some time. At the moment, the possible ways to get around the problem are
- do not generate consensus graphs (no `-C/--consensus-spec` option);
- disable padding (`-O /--poa-padding` set to 0 to disable it);
- run `smoothxg` again: it is not 100% deterministic, so there is a chance that the bug is not always triggered.

**Comment by petersudmant** [comment]
So, one issue it turns out, was that I had set my mash length wayyyy too long (100kb). I reduced it to 10kb and all was resolved.

**Comment by subwaystation** [comment]
Great, thanks for the feedback  @petersudmant !
