### ISSUE TITLE
Setting -n to number of genomes, or number of genomes minus one?

### ISSUE THREAD

**Issue by henrivkgt** [pangenome/pggb#227]
Hello, 

I am trying to run the pggb tool on a set of six cucumber genomes. One thing that is not completely clear to me is how to set the -n parameter. In one doc page (https://pggb.readthedocs.io/en/latest/rst/tutorials/sequence_partitioning.html) a set of 7 yeast genomes is used, with -n representing the number of mappings per locus (which is 6, or the number of genomes minus one). In others, such as the quick start (https://pggb.readthedocs.io/en/latest/rst/quick_start.html) it seems the -n is set to the number of genomes (so not minus one). 

Would you be able to clear this up to me?

Thanks in advance,
Henri

**Comment by AndreaGuarracino** [comment]
Hi @henrivkgt,

those `-n`s are not the same parameter. In the first example (https://pggb.readthedocs.io/en/latest/rst/tutorials/sequence_partitioning.html), `-n` refers to a parameter of `wfmash` (the sequence aligner we use in `pggb`). Instead, in the second example (https://pggb.readthedocs.io/en/latest/rst/quick_start.html), `-n` refers to a parameter of `pggb`.

Since they have the same name, I wonder if we should make the handling of these `-n`s the same from the outside (hiding the -1 thing) to avoid other confusion in the future.

**Comment by henrivkgt** [comment]
Thank you, that makes sense.
