### ISSUE TITLE
ValueError: too many values to unpack (expected 13)

### ISSUE THREAD

**Issue by ld9866** [pangenome/pggb#257]
Dear developer
We are using“ https://pggb.readthedocs.io/en/latest/rst/tutorials/sequence_partitioning.html# ”When analyzing our data with the examples provided, we found that paf2net Py cannot run normally, so we cannot perform subsequent analysis. We also performed the same operation on the test data provided by pggb, whether it is DRB1-3123.fa.gz.f38ac34.alignments.wfmash.paf or our own dye donor file, and the error is reported as follows:
Could you help us?
Thank you!

Code：
python3 /shell/pggb-master/scripts/paf2net.py -p DRB1-3123.fa.gz.f38ac34.alignments.wfmash.paf
Result：
Traceback (most recent call last):
  File "/home/lidong/shell/pggb-master/scripts/paf2net.py", line 18, in <module>
    name1, _, _, _, _, name2, _, _, _, _, align_len, _, est_identity = line.strip().split('\t')
ValueError: too many values to unpack (expected 13)

**Comment by AndreaGuarracino** [comment]
@ld9866, see #256, it could be related. Check the first lines of the `DRB1-3123.fa.gz.f38ac34.alignments.wfmash.paf` file and please let me know.

**Comment by ld9866** [comment]
Hello, l upload the first line here:
Look forward to receiving your reply!

gi|568815529:3998044-4011446	13403	0	13403	+	gi|568815567:3779003-3792415	13413	0	13413	13402	13413	31	gi:f:99.9851	bi:f:99.918	md:f:99.9926	wt:i:13	pt:i:8	aa:i:1	ap:i:1	cg:Z:4896=10D6889=1X1617=



[DRB1-3123.fa.gz.f38ac34.alignments.wfmash.zip](https://github.com/pangenome/pggb/files/10079975/DRB1-3123.fa.gz.f38ac34.alignments.wfmash.zip)

**Comment by AndreaGuarracino** [comment]
Hi @ld9866, the problem is that you are using the output of `wfmash` without adding `-m` as indicated in the tutorial [here](https://pggb.readthedocs.io/en/latest/rst/tutorials/sequence_partitioning.html#community-detection). However, I have just updated the `paf2net` script to support also this kind of PAF file, to avoid other users getting the same problem in the future. Therefore, you can either follow carefully the tutorial or update your `paf2net` script!
