### ISSUE TITLE
run without errors and outputs

### ISSUE THREAD

**Issue by Gon1976** [pangenome/pggb#388]
Hi I am trying to run pggb.
I make a fasta with 7 chromosomes i want to compare of 7 species. I names using PanSN
I run with the basic comand
./pggb -i test.fa  -o out
I have not ouput

Also I tried the examples command lines and I cant run it because PanSN not match:
./pggb -i data/HLA/DRB1-3123.fa.gz -p 70 -s 3000 -G 2000 -n 10 -t 16  -o out -M -m
[pggb] warning: there are sequence names (like 'gi|568815592:32578768-32589835') that do not match the Pangenome Sequence Naming (PanSN)
any idea?
Thanks
Gonzalo

**Comment by AndreaGuarracino** [comment]
PanSN warning should not prevent graph building, but just variant calling, as PanSN became mandatory in recent versions of VG.

Can you share your (bgzipped) sequences? or at least your log file, to check what is going on?
________________________________
From: Gon1976 ***@***.***>
Sent: Tuesday, April 9, 2024 07:50
To: pangenome/pggb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pangenome/pggb] run without errors and outputs (Issue #388)


Hi I am trying to run pggb.
I make a fasta with 7 chromosomes i want to compare of 7 species. I names using PanSN
I run with the basic comand
./pggb -i test.fa -o out
I have not ouput

Also I tried the examples command lines and I cant run it because PanSN not match:
./pggb -i data/HLA/DRB1-3123.fa.gz -p 70 -s 3000 -G 2000 -n 10 -t 16 -o out -M -m
[pggb] warning: there are sequence names (like 'gi|568815592:32578768-32589835') that do not match the Pangenome Sequence Naming (PanSN)
any idea?
Thanks
Gonzalo

**Comment by Gon1976** [comment]
I have not log file. I send my compressed fasta

[test.fa.gz](https://github.com/pangenome/pggb/files/14918811/test.fa.gz)

**Comment by Gon1976** [comment]
Thanks, the version is:
./pggb --version
pggb v0.6.0-0-gd500639

I download from github:
git clone --recursive https://github.com/pangenome/pggb
cd pggb
and try using: ./pggb

**Comment by AndreaGuarracino** [comment]
In that way you've just downloaded the PGGB script, but to be able to run it, you have to install also its components (wfmash, seqwish, ...). The fact that it is not saying anything as error message is a known issue for me, that's silly, I will fix it. Try to install with Docker/Singularity/Bioconda (https://github.com/pangenome/pggb?tab=readme-ov-file#installation).

**Comment by Gon1976** [comment]
ok, i will try, thanks for your support

**Comment by Gon1976** [comment]
I installed tools, and use singularity to run. Works fine
thanks
