### ISSUE TITLE
Docker image build failed

### ISSUE THREAD

**Issue by Pigrenok** [pangenome/pggb#49]
Hello!

I was just trying to build a docker image from the latest Dockerfile and have got errors in compilation of seqwish and smoothxg. If I comment lines 50 and 59 (lines, which checkout specific commits in seqwish and smoothxg repos respectively) and compile the latest versions, everything compiles normally.

After that pddb seems to work just fine (at least on test example), but do not generate diagnostic images (even though options `-v` and `-l` were set).

Is there any particular reason for going to these particular commits or pggb was just tested with these particular versions of the tools?

Thanks.

Best regards,

Vitaly.

**Comment by Pigrenok** [comment]
Update, after rebuilding image, the diagnistic images and MultiQC report was generated. So, it seems removing these `git checkout` commands in Dockerfile does not affect functionality (at least from the use with the test data).

**Comment by subwaystation** [comment]
Hi @Pigrenok,
sorry for the inconveniences!
We use the `git checkout` commands in order to force a specific commit version because `pggb` is still under heavy development and some commits might not be 100% stable or compatible. 
When you removed those lines, your `docker build` command automatically checked out the most recent commit on master at the time of building. You might have been lucky there ;)

With https://github.com/pangenome/pggb/pull/46 we will ship in a much faster and advanced `pggb`. Please be patient until it's there :)

**Comment by Pigrenok** [comment]
Thanks, Simon, for your update.

I would not change Dockerfile of not the problems with compilation of smoothxg and seqwish on these specific commits. 

I even tried to compile them separately on that commits and got the same results (compilation errors). They both fails on including `mio` headers. The latest versions of both tools compile just fine.

What I am trying to say is that probably the selected commits of said tools skills be reviewed. Although, if you are planning major update soon, there is no point to change it now.

**Comment by AndreaGuarracino** [comment]
Hi @Pigrenok, we released the big update! Could you please let us know if you still observe the same problems?

**Comment by Pigrenok** [comment]
Hello, @AndreaGuarracino! Thanks for the update. As I said, I modified the Dockerfile (removed `git checkout` commands) and it all compiled nicely. I will have a look at the updated version.

**Comment by AndreaGuarracino** [comment]
@Pigrenok, you're welcome! Feel free to re-open the issue if you encounter the same problem again.
