### ISSUE TITLE
Bubble popping/gfa-format issue

### ISSUE THREAD

**Issue by kristinastenlokk** [pangenome/pggb#74]
Hi!

After running pggb I would like to check out the variants/bubbles found. I tried using "gfatools bubble" to do this, but there is no output produced when running this on pggb gfa. Is there a known difference in the gfa-format of pggb compared to EG. minigraph causing this, or is there another way to get the variants/bubble-information?

Thanks,
Kristina Stenløkk

**Comment by ekg** [comment]
The pggb output should be a strict subset of what gfatools supports, so this sounds like a bug or hidden limitation of gfatools. The path lines should be ignored by gfatools, and the rest of the graph is just S and L records. This is standard GFA that's been in use for ~6 years.

You can apply `gfautil -i x.gfa gfa2vcf >x.vcf` to obtain the variants in the graph against all embedded references. You may want to specify one reference with `--refs` or `--paths-file`, otherwise it will give you the VCF against all of them. Apply this to the final output GFA file that contains paths for all sequences, not the consensus graph files.

https://crates.io/crates/gfautil

**Comment by kristinastenlokk** [comment]
Thanks for your prompt reply! I will test gfautil.
